version: 2
jobs:
    build:
      working_directory: ~/repo
      docker:
        - image: circleci/node:7
        - image: circleci/python:3.6.1
      steps:
        - checkout
        - setup_remote_docker
        # - run : docker info
        # - run :
        #     name: docker login
        #     command: "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD"
        # - run:
        #     name: docker build
        #     command: "docker build -t my-app ."
        # - run:
        #     name: docker create tag
        #     command: "docker tag my-app joseangelmr/my-app:latest"
        # - run:
        #     name: docker push image
        #     command: "docker push joseangelmr/my-app:latest"
        - run:
            name: server deploy
            command: "sudo apt-get update && sudo apt-get install software-properties-common && sudo apt-add-repository ppa:ansible/ansible -y && udo apt-get install ansible"