version: 2
jobs:
    build:
      working_directory: ~/repo
      docker:
        - image: circleci/node:7
        - image: jonbaldie/yarn:latest
      steps:
        - checkout
        - setup_remote_docker
        - run : yarn install
        - run : yarn test
        - run : docker info
        - run :
            name: docker login
            command: "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD"
        - run:
            name: docker build
            command: "docker build -t my-app ."
        - run:
            name: docker push image
            command: "docker push joseangelmr/my-app:$CIRCLE_BRANCH"