version: 2
jobs:
    build:
      working_directory: ~/repo
      docker:
        - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: yarn install
        - run: yarn test
        - run: ls
        - run:
          name: docker login
          command: |
            - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
        - run:
          name: docker build
          command: |
            - docker build -t my-app .