version: 2
jobs:
    build:
      working_directory: ~/repo
      docker:
        - image: circleci/node:7
        - image: jonbaldie/yarn:latest
      steps:
        - checkout
        - run: yarn install
        - run: yarn test
        - run: ls