---
- name: Deploy application
  hosts: aws-server
  vars_files:
    - ["vars/default.yml"]
  become: True
  tasks:
    - name: Create a data container
      docker_container:
        name: my-app
        image: joseangelmr/my-app:latest
        recreate: yes
        pull: yes
        ports:
          - 3000:3000
        volumes:
          - /data